### ISSUE TITLE
git clone problem

### ISSUE THREAD

**Issue by aogrcs** [stephen99scott/cFS-stm32l4#1]
Hi,
I clone this code and update it, but it give the following error:
![屏幕截图 2023-05-08 221409](https://user-images.githubusercontent.com/5660925/236847753-2724f402-7bbf-4521-bca1-738b5698dfde.jpg)

**Comment by stephen99scott** [comment]
This seems like an issue specific to your machine, could be the ssh key or outdated known hosts. Try deleting ~/.ssh/known_hosts or generate a new key.

**Comment by stephen99scott** [comment]
https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/ could be related

**Comment by aogrcs** [comment]
> https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/ could be related

Thanks, it works, hope for more communication
